import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

/* Usable Design System: Inter font family for all text */
/* Weights: 300 (light), 400 (regular), 600 (semibold), 700 (bold), 900 (black) */
const inter = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
	weight: ["300", "400", "600", "700", "900"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={inter.variable}>
			<body className={`${inter.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
